### ISSUE TITLE
To define the content of the template README.md

### ISSUE THREAD

**Issue by helio-frota** [helio-frota/falta#1]
Currently the template README.md has the following content:

```
A basic readme.
```

**Comment by lholmquist** [comment]
Since this JIRA issue was an investigation,  I don't think we need to come up with a fully flushed out readme, since that wording will probably need to come from a PM or similar.

The fact that a readme is created during this process is good enough for this investigation

**Comment by helio-frota** [comment]
sounds good, closing then :+1:
