### ISSUE TITLE
To define some error message when failing the postinstall

### ISSUE THREAD

**Issue by helio-frota** [helio-frota/falta#3]
Currently it fails with no custom message.

**Comment by lholmquist** [comment]
Again,  the error message will probably be defined similar to the readme.

This is the module i made that actually is able to use chalk to style the error message, https://github.com/lholmquist/always-fail

My thought is that the output of falta would will essentially create something like that.

**Comment by helio-frota** [comment]
Sounds good, thanks.
Updated https://github.com/helio-frota/falta/blob/master/templates/fail.js#L1
