### ISSUE TITLE
To understand what happen with the project name when publishing to npm 

### ISSUE THREAD

**Issue by helio-frota** [helio-frota/falta#4]
Seems the default is that `create-` will be automatically added to the name or something like that.
It would be good to have a way to test it locally (manually) before publish to npm.

**Comment by lholmquist** [comment]
So the `create-` will only get added if a user uses the "init" command,  https://docs.npmjs.com/cli/init

so doing `npm init falta .` would actually be equal to  a call to `npx create-falta`

So this is the point were we decide if we want a user to use "npm init" or just have them call the module directly with "npx/npm"

**Comment by lholmquist** [comment]
I sort of like the "npx create-thing" flow,  so in that case "npm init thing" will work too.

If we want to test it out,  you could always publish this to your namespace on npm

**Comment by helio-frota** [comment]
yeah , probably good to publish and see what happen.

**Comment by helio-frota** [comment]
Published, it seems to work but without the "create-" name

```console
[.~/abc] npx falta myapp myAppName
npx: installed 3 in 2.291s
[.~/abc] tree myapp/
myapp/
├── fail.js
├── package.json
└── README.md

0 directories, 3 files
[.~/abc] cd myapp/
[.~/abc/myapp] npm i

> myAppName@0.0.0 postinstall ~/abc/myapp
> node fail.js

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myAppName@0.0.0 postinstall: `node fail.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myAppName@0.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2020-06-26T15_48_54_804Z-debug.log
```

**Comment by helio-frota** [comment]
I think we can probably close this, we can reopen if needed
